theme: charlolamode
copyright: made by MizouziE
baseURL: https://mizouzie.github.io/
title: web with mizouzie
paginate: 5

menu:
    main:
        - name: Contact
          url: /contact/
          weight: 30
        - name: Articles
          url: /articles/
          weight: 10
        - name: Projects
          url: /projects/
          weight: 20

        - name: Categories
          url: /categories/
          weight: 15
        # - name: new Tab
        #   url: /newtab/
        #   weight: defines order of tabs
   


params:
    author: Sam Anglin


    defaultTheme: auto
    # disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: true
    displayFullLangName: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    ShowToc: true

    profileMode:
        # Disable to populate home page with 'mainSections' content
        enabled: true
        title: MizouziE
        description: |

          Hello, I am Sam
            the web application developer. 
        

          Here I'll show you some of what I can do, as well as a bunch of stuff that I think about.
        imageUrl: "/images/profile-pic.png"
        imageTitle: my image
        # imageWidth: 120
        # imageHeight: 120
        buttons:
            - name: About me
              url: /about/
    mainSections:
      - articles

    socialIcons:
        # - name: buymeacoffee
          # url: "https://ko-fi.com/heycharlola"
        - name: youtube
          url: "https://www.youtube.com/mizouzie"
        - name: twitter
          url: "https://twitter.com/mizouzie"
        - name: github
          url: "https://github.com/mizouzie"
        - name: instagram
          url: "https://www.instagram.com/mizouzie/"
        - name: linkedin
          url: "https://www.linkedin.com/in/sam-anglin/"

      # add more social icons. find more in svg.html file
      # - name: facebook
      #   url: yoururl


    # change favicon in images folder (icon for web tab)
    assets:
          favicon: "/images/favicon.ico"
          favicon16x16: "/images/favicon-16x16.png"
          favicon32x32: "/images/favicon-32x32.png"
          apple_touch_icon: "/images/apple-touch-icon.png"
          safari_pinned_tab: "/images/apple-touch-icon.png"
          ogImage: "/images/social.png"
          ogImageWidth: 1190
          ogImageHeight: 627

    description: "MizozuiE the web app developer, on this page you'll find contact details, a blog, links to social media and other interesting projects that have been worked on."



enableInlineShortcodes: true
enableRobotsTXT: true
enableEmoji: true
pygmentsUseClasses: true

minify:
    disableXML: true
