theme: charlolamode
copyright: made by MizouziE
baseURL: # if your site is in 'https', then make sure your base url isn't written using 'http' otherwise your sitemap would contain http (as opposeed to https) URLs. This would affect Google indexing of your URLs.
title: web with mizouzie
paginate: 5

menu:
    main:
        - name: Contact
          url: /contact/
          weight: 30
        - name: Articles
          url: /articles/
          weight: 10
        - name: Projects
          url: /projects/
          weight: 20

        - name: Categories
          url: /categories/
          weight: 15
        # - name: new Tab
        #   url: /newtab/
        #   weight: defines order of tabs
   


params:
    author: Sam Anglin


    defaultTheme: auto
    # disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: true
    displayFullLangName: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    ShowToc: true

    profileMode:
        # Disable to populate home page with 'mainSections' content
        enabled: true
        title: MizouziE
        description: |

          Hello, I am Sam
            the web application developer. 
        

          Here I'll show you some of what I can do, as well as a bunch of stuff that I think about.
        imageUrl: "/images/profile-pic.png"
        imageTitle: my image
        # imageWidth: 120
        # imageHeight: 120
        buttons:
            - name: About me
              url: /about/
    mainSections:
      - articles

    socialIcons:
        # - name: buymeacoffee
          # url: "https://ko-fi.com/heycharlola"
        - name: github
          url: "https://github.com/mizouzie"
        - name: linkedin
          url: "https://www.linkedin.com/in/sam-anglin/"
        - name: twitter
          url: "https://twitter.com/mizouzie"
        - name: instagram
          url: "https://www.instagram.com/mizouzie/"

      # add more social icons. find more in svg.html file
      # - name: youtube
      #   url: yoururl
      # - name: facebook
      #   url: yoururl


    # change favicon in images folder (icon for web tab)
    assets:
          favicon: "/images/favicon.ico"
          favicon16x16: "/images/favicon-16x16.png"
          favicon32x32: "/images/favicon-32x32.png"
          apple_touch_icon: "/images/apple-touch-icon.png"
          safari_pinned_tab: "/images/apple-touch-icon.png"



enableInlineShortcodes: true
enableRobotsTXT: true
enableEmoji: true
pygmentsUseClasses: true

minify:
    disableXML: true